# Generated by Django 4.2.7 on 2023-11-28 11:24

from django.db import migrations

def crearInitialData(apps, schema_editor):
    Libro = apps.get_model('storeapp', 'Libro')
    Editorial = apps.get_model('storeapp', 'Editorial')
    Autor = apps.get_model('storeapp', 'Autor')

    if not Libro.objects.filter(isbn='9788445000656').exists():

        editorial = Editorial.objects.create(name='Allen & Unwin')
        autor = Autor.objects.create(name='J. R. R. Tolkien')

        libro = Libro.objects.create(
            isbn='9788445000656',
            titulo='El Hobbit',
            edicion='1982',
            pag=301,
            desc='La trilogía de El hobbit, adaptación cinematográfica basada en la novela homónima, comprende tres películas épicas de fantasía, acción y aventuras: El hobbit: un viaje inesperado, El hobbit: la desolación de Smaug y El hobbit: la batalla de los Cinco Ejércitos.',
            editorial=editorial,
        )
        libro.autores.add(autor)

class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial')
    ]

    operations = [
        migrations.RunPython(crearInitialData)
    ]